app1/urls.py
from django.urls import path
from .views import *
app_name='app1'

urlpatterns = [
    path('base/1234',base,name='baseurls'),
    path('base/5678',base,name='baseurls'),
    path('',index,name='indexurls'),
    path('callback/',callback,name='callbackurls'),
    path('about/',about,name='abouturls'),
    path('policy-policy/',policy,name='policyurls'),
]

medictrl/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin123321123", admin.site.urls),
    path('',include('app1.urls',namespace='app1')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app1/models.py
from distutils import text_file
from email.policy import default
from django.db import models

class message(models.Model):
    name=models.CharField(max_length=50)
    phone=models.FloatField()
    city=models.CharField(max_length=50)
    state=models.CharField(max_length=50)
    message=models.TextField()

app1/forms.py
from dataclasses import field
from itertools import product
from django import forms
from app1.models import *


class message_Form(forms.ModelForm):
    class Meta:
        model=message
        fields='__all__'

app1/views.py
from django.shortcuts import render,redirect
from app1.forms import *
from django.core.mail import send_mail


app_name="app1"


def base(request):
    return render(request,'base.html')

def base2(request):
    return render(request,'base2.html')
def index(request):
    return render(request,'app1/index.html')
def callback(request):
    if request.method =="POST":
        form=message_Form(request.POST)
        if form.is_valid():
            form.save()
            send_mail(
                'New Message',
                'New Message from Site',
                'contactmedictrl@gmail.com',
                ['shardulanand1@gmail.com'] ,
                fail_silently=False,
            )
        else:
            print(form.errors)
            return redirect('app1:indexurls')
    form=message_Form()
    context={
        'form':form,
    }
    return render(request,'app1/callback.html',context)
def about(request):
    return render(request,'app1/aboutus.html')
def policy(request):
    return render(request,'app1/privacy.html')

app1/templates/app1/aboutus.html
{% load static %}
<title>About us </title>
{% block body %}
{% block content %}
<link rel="stylesheet" href="{% static 'app1/css/about.css' %}">
<link rel="shortcut icon" href="{% static 'app1/img/favicon.png' %}">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<script src="https://kit.fontawesome.com/0ca0033246.js" crossorigin="anonymous"></script>

<div class="header">
    <img src= {% static 'app1/img/logo-white.png' %}>
    <a href="javascript:void(0);" class="icon" onclick="myFunction()">
    <i class="fa fa-bars"></i>
</div>
    <div class="topnav" id="myTopnav">
            <a class='button' href="{% url 'app1:indexurls' %}"><b>Home</b></a>
            <a class='button' href="/#services"><b>Services</b></a>
            <a class='button' href="/#Hospitals"><b>Hospitals</b></a>
            <a class='button' href="{% url 'app1:abouturls' %}"><b>About us</b></a>
            <a class='button1'  href="{% url 'app1:callbackurls' %}"><b>Get A Call Back</b></a>
    </div>
</div>

<div class="about">
<img src= {% static 'app1/img/about.png' %}>
</div>
<div class="about_info">
    <h2>Our Mission</h2>
    <p>With an aim to create a network of top-notch hospitals<br>
        called Medictrl is committed to offering topnotch medical<br>
        treatment to everyone.<br><br>
        With the help of Medictrl's innovative solutions, hospitals<br>
        can treat patients more affordably, provide them a better<br>
        overall experience, and uphold high standards for medical<br>
        quality with the goal of building a hospital network that<br>
        patients can rely on for excellent results, price<br>
        transparency, and a top-notch experience.
    </p>
</div>
<div class="team">
    <h2>Our Team</h2>
    <p>The ones working day night to give you the platform for all your<br>healthcare needs.</p>
</div>
<div class="teaminfo1">
    <img src= {% static 'app1/img/varun.jpg' %}>
    <h5>Varun Kumar Singh <a href="https://www.linkedin.com/in/varun-singh-vs0920/"><i class="fa-brands fa-linkedin"></i></a></h5>

    <p><b>Chief Executive Officer</b></p>
    <div class="ex">
        <p>11+ years of experience in healthcare. Track record of business development, strategic, relationship management, network management, new city launching, & ancillary revenue stream, key accounts management, Innovation, Startups(Healthcare).</p>
    </div>
</div>
<div class="teaminfo2">
    <img src= {% static 'app1/img/ratul.jpg' %}>
    <h5>Ratul Majmudar <a href="https://www.linkedin.com/in/ratul-majumdar-69b46038/"><i class="fa-brands fa-linkedin"></i></a></h5>
    <p><b>Chief Operating Officer</b></p>
    <div class="ex2">
        <p>17+ years of experience in healthcare. Rich expertise in Overall Hospital Business Development and Management and Strategic Medical Recruitment.</p>
    </div>
</div>
<div class="teaminfo3">
    <img src= {% static 'app1/img/shoumya.jpg' %}>
    <h5>CA Shoumya Hor <a href="https://www.linkedin.com/in/ca-shoumya-hor-8033a55/"><i class="fa-brands fa-linkedin"></i></a></h5>
    <p><b>Chief Financial Officer</b></p>
    <div class="ex3">
        <p>Chartered Accountant having 25 + years of experience Worked as CFO s in major Indian Companies Mahindra Group Company and MNCs such as Husco Hydraulics a subsidiary of US MNC, and Hyundai Construction Equipment</p>
    </div>
</div>
<div class="teaminfo4">
    <img src= {% static 'app1/img/cto.png' %}>
    <h5>Dummy <a href="###"><i class="fa-brands fa-linkedin"></i></a></h5>
    <p><b>Chief Technical Officer</b></p>
    <div class="ex3">
        <p>An IIT alumnus and startup enthusiastic who has served in 3 startups as a founding team member. Naresh is a software engineer who have worked for more than 7 years before joining us</p>
    </div>
</div>
<div class="teaminfo5">
    <img src= {% static 'app1/img/rankit.jpg' %}>
    <h5>Rankit Singh <a href="https://www.linkedin.com/in/rankit-singh/"><i class="fa-brands fa-linkedin"></i></a></h5>
    <p><b>Founding Team</b></p>
    <div class="ex3">
        <p>Passionate about entrepreneurship & startup culture. Worked and curated data in healthcare business startup.Experienced in building startups from ideation.</p>
    </div>
</div>
<script>
    function myFunction() {
      var x = document.getElementById("myTopnav");
      if (x.className === "topnav") {
        x.className += " responsive";
      } else {
        x.className = "topnav";
      }
    }
  </script>
{% endblock content %}
{% endblock body %}

app1/templates/app1/callback.html
{% load static %}
<title>Contact | MediCTRL</title>
{% block body %}
{% block content %}
<link rel="stylesheet" href="{% static 'app1/css/stylecall.css' %}">    
<link rel="shortcut icon" href="{% static 'app1/img/favicon.png' %}">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<script src="https://kit.fontawesome.com/0ca0033246.js" crossorigin="anonymous"></script>

<body>
    <div class="header">
        <img src= {% static 'app1/img/logo-white.png' %}>
        <a href="javascript:void(0);" class="icon" onclick="myFunction()">
        <i class="fa fa-bars"></i>
    </div>
        <div class="topnav" id="myTopnav">
                <a class='button' href="{% url 'app1:indexurls' %}"><b>Home</b></a>
                <a class='button' href="#services"><b>Services</b></a>
                <a class='button' href="#Hospitals"><b>Hospitals</b></a>
                <a class='button' href="{% url 'app1:abouturls' %}"><b>About us</b></a>
                <a class='button1'  href="{% url 'app1:callbackurls' %}"><b>Get A Call Back</b></a>
        </div>
    </div>
    <div class="main">
        <img src= {% static 'app1/img/contact.jpg' %}>
        <h3>Got A Problem</h3>
        <p>Leave your message here and we will reach you within 24 hours</p>
    </div>
    <div class="form">
        <form action="" method="post">
            {% csrf_token %}
        <table>
            <tr>
                <td><input type="text" id="name" name='name' placeholder="Name*"></td>
                <td><input type="numbers" id="number" name='phone' placeholder="phone*"></td>
            </tr>
            <tr>
                <td><input type="text" id="city" name='city' placeholder="City*"></td>
                <td><input type="text" id="state" name='state' placeholder="State*"></td>
            </tr>
            <tr>
                <td><textarea name="message"  cols="30" row="5"  placeholder="Message*"></textarea></td>
            </tr>
            <tr>
                <td><input type='submit' value='Send' style='background-color:#4883B0;font-family:helvetica;border: 
                    none;color: white;padding: 10px 10px;text-align: center;text-decoration: none;display: inline-block;
                    ;cursor: pointer;border-radius: 16px;margin: 130px 0px; font-family:helvetica;'></td>
            </tr>
        </table>
    </div>
    <script>
        function myFunction() {
          var x = document.getElementById("myTopnav");
          if (x.className === "topnav") {
            x.className += " responsive";
          } else {
            x.className = "topnav";
          }
        }
      </script>
</body>
{% endblock content %}
{% endblock body %}

app1/templates/app1/index.html
{% load static %}
<title>Home | MediCtrl</title>
{% block body %}
{% block content %}
<link rel="stylesheet" href="{% static 'app1/css/style.css' %}">
<link rel="shortcut icon" href="{% static 'app1/img/favicon.png' %}">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<script src="https://kit.fontawesome.com/0ca0033246.js" crossorigin="anonymous"></script>

<body>
  <div class="header">
    <img src= {% static 'app1/img/logo-white.png' %}>
    <a href="javascript:void(0);" class="icon" onclick="myFunction()">
    <i class="fa fa-bars"></i>
</div>
    <div class="topnav" id="myTopnav">
            <a class='button' href="{% url 'app1:indexurls' %}"><b>Home</b></a>
            <a class='button' href="#services"><b>Services</b></a>
            <a class='button' href="#Hospitals"><b>Hospitals</b></a>
            <a class='button' href="{% url 'app1:abouturls' %}"><b>About us</b></a>
            <a class='button1'  href="{% url 'app1:callbackurls' %}"><b>Get A Call Back</b></a>
    </div>
</div>

  <section id="intro">
  {% comment %} <div class="intro"> {% endcomment %}
      <h3>Feel control of your <br>medical journey with <br>MediCtrl</h3>
      <p>The top doctors, technology and treatment are accessible in your town.<br>
          Schedule a free appointment with one of our expert doctors near you.</p>
            <div class="button2">
              <a href="{% url 'app1:callbackurls' %}"><b>Talk to us</b></a>
          </div> 
      <img src= {% static 'app1/img/home.png' %}>
  {% comment %} </div>         {% endcomment %}
        </section>
  {% comment %} <div class="services"> {% endcomment %}
    <section id="services">
    <p>What services does</p>
    <h1>Medictrl Provide?</h1>
    </section>
  <div class="services-info">
    <div class="info1">
      <img src= {% static 'app1/img/doctors.png' %} >
      <h4>Best doctors and technology</h4>
      <p>Our team of medical professionals ensure that you and your loved ones receive the best medical treatment possible.</p>
    </div>
    <div class="info2">
      <img src= {% static 'app1/img/fixed.png' %} >
      <h4>100% fixed price packages and billing transparency</h4>
      <p>We believe in total openness and zero hidden fees so you may concentrate on your healthcare.</p>
    </div>
    <div class="info3">
      <img src= {% static 'app1/img/pre.png' %} >
      <h4>Pre and post-hospitalization assistance</h4>
      <p>Consultations and instructions including dietary tips as well as exercises to every patients.</p>
    </div>
    <div class="info4">
      <img src= {% static 'app1/img/insurance.png' %} >
      <h4>Insurance support and medical financing</h4>
      <p>Hospitals with medi-loans facilities and insurance tie-ups to ensure hassle free insurance claims.</p>
    </div>
    <div class="info5">
      <img src= {% static 'app1/img/call.png' %} >
      <h4>Escort for need fulls</h4>
      <p>Caretaker for the elderly & needfulls, as well as pick-up and drop-off aid.</p>
    </div>
    <div class="info6">
      <img src= {% static 'app1/img/slot.png' %} >
      <h4>User-friendly tech for slot booking and other services</h4>
      <p>For the patient's convenience, live tracking and slot booking for OPD are available.</p>
    </div>
  </div>
  <div class="services-2">
    <p>How it works?</p>
    <h1><b>Discover MediCtrl Benifits!</b></h1>
    <p>With just few clicks</p>
    <h7><b>All your healthcare need,
      one stop MediCtrl</b></h7>
    <img src= {% static 'app1/img/idea.png' %} >
  </div><br>
  <div class="services-tick">
    <p><i class="fa-regular fa-circle-check"></i>&nbsp&nbsp&nbsp Book your appointment through MediCtrl website</p>
    <p><i class="fa-regular fa-circle-check"></i>&nbsp&nbsp&nbsp After confirmation via call, visit MediCtrl hospital</p>
    <p><i class="fa-regular fa-circle-check"></i>&nbsp&nbsp&nbsp Get your prescription on the app</p>
    <p><i class="fa-regular fa-circle-check"></i>&nbsp&nbsp&nbsp Select your diagnosis and order medicines through the app</p>
    <p><i class="fa-regular fa-circle-check"></i>&nbsp&nbsp&nbsp Earn rewards on the services you avail</p>
  </div>
  {% comment %} <div class="Hospitals"> {% endcomment %}
    <section id="Hospitals">
    <p>Who are our partner health providers</p>
    <h1><b>MediCtrl Hospitals</b></h1>
    </section>
  <div class="Hospitals-pic">
    <img src= {% static 'app1/img/apple.jpeg' %} >
    <img src= {% static 'app1/img/apple.jpeg' %} >
    <img src= {% static 'app1/img/apple.jpeg' %} >
    <img src= {% static 'app1/img/apple.jpeg' %} >
  </div>
  <div class="Hospitals-info">
    <div class="hospital-info1">
      <img src= {% static 'app1/img/Locations.png' %} >
      <p><b>1</b> City Present</p>
    </div>
    <div class="hospital-info2">
      <img src= {% static 'app1/img/plus.png' %} >
      <p><b>1</b> Hospital Onboard</p>
    </div>
    <div class="hospital-info3">
      <img src= {% static 'app1/img/beds.png' %} >
      <p><b>25</b> Beds strength</p>
    </div>
    <div class="hospital-info4">
      <img src= {% static 'app1/img/Patients.png' %} >
      <p><b>0</b> Patients Served</p>
    </div>
  </div>
  <div class="partners">
    <p>We are backed by strong firms</p>
    <h1><b>Our Partners</b></h1>
    <img src= {% static 'app1/img/incubator.png' %} >
    <img src= {% static 'app1/img/startup.png' %} >
  </div>
  <div class="FAQ">
    <p>Everything you need to know</p>
    <h1><b>Frequently Asked Questions</b></h1>
  </div>
  {% comment %} FAQ {% endcomment %}
  <main>
    <section id="faq-container">
        <div class="faq-one">
            <!-- faq question -->
            <h1 class="faq-page">How does MediCtrl ensure good medical quality?</h1>
            <!-- faq answer -->
            <div class="faq-body">
                <p>All MediCtrl hospitals are accredited by National Accreditation Board for Hospitals & Healthcare Providers
                   (NABH), dictated on ground MediCtrl works on healthcare parameters & patient experience ..</p>
            </div>
        </div>
        <hr class="hr-line">
        <div class="faq-two">
            <!-- faq question -->
            <h1 class="faq-page">What does fixed price package include?</h1>
            <!-- faq answer -->
            <div class="faq-body">
                <p>The fixed price package typically covers all costs associated with the surgery. This typically includes: i) 
                  Hospital admission charges. ii) Surgery charges including surgeon fees, anesthetist fees and OT charges. iii)
                   Hospital stays. iv) Cost of drugs consumed during stay at hospital</p>
            </div>
        </div>
        <hr class="hr-line">
        <div class="faq-three">
            <!-- faq question -->
<h1 class="faq-page">Does MediCtrl provide a second opinion for any disease?</h1>
            <!-- faq answer -->
            <div class="faq-body">
                <p>Yes, you can avail second medical opinion by specialized doctors for all diseases. Our doctor tracks your 
                  pathology reports, your post-operative report, your discharge summary, and guides you with the required/ new 
                  treatment course ahead.</p>
            </div>
        </div>
        <hr class="hr-line">
        <div class="faq-two">
            <!-- faq question -->
            <h1 class="faq-page">What MediCtrl provide insurance coverage for all surgeries?</h1>
            <!-- faq answer -->
            <div class="faq-body">
                <p>MediCtrl assists you in getting the insurance approval done within 30 minutes.. 
                  Your insurance coverage depends on the health insurance type (personal, corporate) and the terms and 
                  conditions set by the insurance provider.</p>
            </div>
        </div>
        <hr class="hr-line">
        <div class="faq-two">
            <!-- faq question -->
            <h1 class="faq-page">What MediCtrl have its own Hospitals?</h1>
            <!-- faq answer -->
            <div class="faq-body">
                <p>MediCtrl does have its own hospital and MediCtrl also works in association with other hospitals to provide 
                  medical facility by hospital and non medical facility by MediCtrl.</p>
            </div>
        </div>
    </section>
</main>
<div class="footer">
  <br>
  <div class="namemail">
    <a href="tel:+4733378901">+91 9871093589</a>
    <a href="mailto:someone@example.com">info@medictrl.com</a>
  </div>
  {% comment %} l {% endcomment %}
  <div class="social">
    <h1>Social Share</h1>
  </div>
  <div class="fonts" data-aos="fade-up">
    <a href="https://www.linkedin.com/company/medictrl/"><i class="fa-brands fa-linkedin"></i></a>
    <a href="https://www.facebook.com/MediCtrl"><i class="fa-brands fa-facebook-f"></i></a>
    <a href="https://www.instagram.com/medictrl_/"><i class="fa-brands fa-instagram"></i></a>
  </div>
  <div class="links">
    <a href="{% url 'app1:indexurls' %}">Home</a>
    <a href="###">About</a>
    <a href="#services">Services</a>
    <a href="#Hospitals">Hospitals</a>
    <a href="###">Contact</a>
  </div>
  <div class="links2">
    <a href="https://docs.google.com/forms/d/e/1FAIpQLSdWs_hKSXl7z0VWGp89J-Dw3nb0uoG0V7Synxz1hYRlSESF3w/viewform">Partner</a>
    <a href="###">Investor</a>
    <a href="###">FAQ</a>
    <a href="https://angel.co/company/medictrl/jobs">Careers</a>
  </div>
  <div class="disclaimer"><br>
    <div class="copyright">
      <p>© 2022-2023 Carpediem Health Experts Private Limited. All rights reserved.</p>
    </div>
    <div class="policy">
      <a href="{% url 'app1:policyurls' %}">Privacy policy</a>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
      <a href="###">Terms and conditions</a>
    </div>
  </div>
</div>

{% comment %} ##4883B0 {% endcomment %}







<script>
var faq = document.getElementsByClassName("faq-page");
var i;
for (i = 0; i < faq.length; i++) {
    faq[i].addEventListener("click", function () {
        /* Toggle between adding and removing the "active" class,
        to highlight the button that controls the panel */
        this.classList.toggle("active");
        /* Toggle between hiding and showing the active panel */
        var body = this.nextElementSibling;
        if (body.style.display === "block") {
            body.style.display = "none";
        } else {
            body.style.display = "block";
        }
    });
}
  </script>
  <script>
    function myFunction() {
      var x = document.getElementById("myTopnav");
      if (x.className === "topnav") {
        x.className += " responsive";
      } else {
        x.className = "topnav";
      }
    }
  </script>
{% endblock content %}
{% endblock body %}

app1/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>{% block title %}{% endblock title %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
        <script src="https://kit.fontawesome.com/0ca0033246.js" crossorigin="anonymous"></script>
        <link rel="shortcut icon" href="{% static 'app1/img/favicon.png' %}">
        <link rel="stylesheet" href="{% static 'app1/css/style.css' %}">
    </head>
    <style>
        .body{
            background-color:#f7f7f7;
        }
        .header{
            background-color:#4883B0;
            height:128px;
            margin-top:-8px;
            margin-left:-8px;
            margin-right:-8px;
        }
        .header img{
            height:60px;
            margin-left:190px;
            margin-top:30px;
        }
        .ref{
            background-color:#4883B0;
            margin-left:800px;
            margin-top:-50px;
        }
        .button {
            background-color: #506690;
            font-family:Sans-serif;
            border: none;
            color: white;
            padding: 10px 25px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            cursor: pointer;
            border-radius: 16px;
          }
        .button1 {
            background-color: #00d663;
            font-family:helvetica;
            border: none;
            color: white;
            padding: 10px 20px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            margin: 4px 8px;
            cursor: pointer;
            border-radius: 16px;
          }
          .button1 a{
            text-decoration: none;
            font-family:helvetica;
            color: white;
          }
          .button2{
            background-color: #48B4BB;
            font-family:helvetica;
            border: none;
            color: white;
            padding: 10px 20px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            margin-left:190px;
            margin-top:-50px;
            cursor: pointer;
            border-radius: 16px;
          }
          {% comment %} Media Query {% endcomment %}
          @media(max-width:480px){
            .header{
              background-color:#4883B0;
              height:70px;
              margin-top:-8px;
              margin-left:-8px;
              margin-right:-8px;
          }
          .header img{
            height:40px;
            margin-left:15px;
            margin-top:15px;
          }
          .ref{
            background-color:#4883B0;
            margin-left:800px;
            margin-top:-50px;
        }
        .button {
          background-color: #506690;
          font-family:Sans-serif;
          border: none;
          color: white;
          padding: 0px 0px;
          cursor: pointer;
        }
        .button a{

        }
















          }

    </style>
    <body>
        <div class="header">
            <img src= {% static 'app1/img/logo-white.png' %}>
            <div class="ref">
                    <a class='button' href="{% url 'app1:indexurls' %}"><b>Home</b></a>
                    <a class='button' href="#services"><b>Services</b></a>
                    <a class='button' href="#Hospitals"><b>Hospitals</b></a>
                    <a class='button' href="#faq-container"><b>FAQ</b></a>
                    <a class='button' href="{% url 'app1:abouturls' %}"><b>About us</b></a>
            <div class="button1">
                <a href="{% url 'app1:callbackurls' %}"><b>Talk to us</b></a>
            </div> 
        </div>
        {% block body %}
        {% block content %}
        {% endblock content %}
        {% endblock body %}
</html>

{% comment %} <button class="button" onclick="location.href='###  "><b>Home</button>
    <button class="button" onclick="location.href='###"><b>Services</button>
    <button class="button" onclick="location.href='###"><b>Hospitals</button>
    <button class="button" onclick="location.href='###"><b>FAQ</button>
    <button class="button" onclick="location.href='###"><b>About us</button>
     {% endcomment %}